create extension if not exists "citext" with schema "public";

create table users (
  id int not null primary key generated by default as identity,
  email citext not null,
  password_hash text not null
);

create unique index users_email_idx on users (email);
